### ISSUE TITLE
As an owner I can't edit any information of my organisation because of the KvK check.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1328]
## Main asssignee: @

start from branch release-v0.6.0

## Context/goal: 
If I already have an organisation  I can't edit any information of the organisation.
After clicking *Confirm* a new request to check if the KvK number is already being used is send to the backend. It will give an error that KvK is already being used.

### Solution
Please make a distinction between editing and creating an organisation

<img width="919" alt="Screen Shot 2019-12-20 at 12 05 03" src="https://user-images.githubusercontent.com/38419514/71251034-7611ea80-2321-11ea-86e7-c3fc73408562.png">

**Comment by maxvisser** [comment]
Done

**Comment by GerbenBosschieter** [comment]
This issue was or not fixed properly, or something the problem is back again.
This fix should be in 0.6.0. Tested this on production, doesn't work yet.
